apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-code
data:
  consumer.py: |
    import pika

    connection = pika.BlockingConnection(
        pika.ConnectionParameters('rabbitmq', 5672)
    )
    channel = connection.channel()
    channel.queue_declare(queue='demo-queue')

    def callback(ch, method, properties, body):
        print(f" [x] Received {body}")

    channel.basic_consume(queue='demo-queue', on_message_callback=callback, auto_ack=True)
    print(' [*] Waiting for messages. To exit press CTRL+C')
    channel.start_consuming()
